### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by FunmiSomoye-schl** [ds5010/vaccines-3#17]
Make Readme up-to-date with new changes

**Comment by FunmiSomoye-schl** [comment]
first one

**Comment by FunmiSomoye-schl** [comment]
This is still open

**Comment by FunmiSomoye-schl** [comment]
Updated first half.
Additional update to link the proper names to their github pages would still need to be done.

**Comment by joschw01** [comment]
https://github.com/joschw01 - Joe Schweiss

**Comment by tom2470** [comment]
Tom Henehan-tom2470

**Comment by dobnu** [comment]
Dan O'Brien
dobnu

**Comment by Moshati1315** [comment]
Mohammed Shati
Moshati1315
https://github.com/Moshati1315

**Comment by Phitran-neu** [comment]
Philip Tran 
Phitran-neu
https://github.com/Phitran-neu

**Comment by mhorns** [comment]
Mitch Hornsby
https://github.com/mhorns

**Comment by petersternhagen** [comment]
Peter Sternhagen
https://github.com/petersternhagen

**Comment by smr-j** [comment]
Jayati Samar
smr-j
https://github.com/smr-j
